/** @internal One ordered inventory for reporting, examples and acceptance reconciliation. */
export const liveReportSuites = [
  'oauth-service-reads',
  'scan',
  'management',
  'model-security',
  'red-team',
  'gateway-read',
  'gateway-analytics-filters',
  'gateway-analytics-request-filters',
  'gateway-analytics-chart-filters',
  'gateway-analytics-chart-filters-sdk',
  'gateway-extensions',
  'gateway-usage-reset',
  'gateway-usage-reset-audit',
  'gateway-mcp-discovery',
  'gateway-mcp-discovery-audit',
  'gateway-mcp-synthetic',
  'gateway-mcp-public',
  'gateway-mcp-fixture-audit',
  'gateway-owned-writes',
  'gateway-secret-references',
  'gateway-model-pricing',
  'gateway-authoring-discovery',
  'gateway-secret-reference-discovery',
  'gateway-runtime-authoring',
  'gateway-provider-http',
  'gateway-provider-http-sdk',
  'gateway-deployment-diagnostics',
  'cli',
  'cli-analytics',
  'cli-writes',
  'gateway-inference',
  'gateway-observability',
  'gateway-runtime-observability',
  'gateway-observability-audit',
  'gateway-observability-details',
  'gateway-observability-details-sdk',
  'gateway-feedback-scores',
  'gateway-legacy-completions',
  'gateway-legacy-completions-sdk',
  'gateway-prompt-runtime',
  'gateway-prompt-runtime-sdk',
  'gateway-realtime',
  'gateway-realtime-sdk',
  'gateway-realtime-example',
  'gateway-realtime-audit',
  'gateway-runtime-resources',
  'gateway-batches',
  'gateway-batches-cancel',
  'gateway-vector-batches',
  'gateway-vector-batches-json',
  'gateway-vector-batches-beta',
  'cli-inference',
  'doc-examples',
  'doc-gateway-key',
  'recover-interrupted',
  'dlp-recovery',
  'dlp-dictionary-wire',
  'cleanup-runtime-audit',
  'cleanup-audit',
] as const;

/** Diagnostic passes validate observations; they do not count as passing service operations. */
export const runtimeDiagnosticSuites = [
  'gateway-observability-details-sdk',
  'gateway-feedback-scores',
  'gateway-legacy-completions',
  'gateway-legacy-completions-sdk',
  'gateway-prompt-runtime',
  'gateway-prompt-runtime-sdk',
  'gateway-realtime',
  'gateway-realtime-sdk',
  'gateway-runtime-authoring',
  'gateway-provider-http',
  'gateway-provider-http-sdk',
  'gateway-deployment-diagnostics',
] as const;
