import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import type {PrismTheme} from 'prism-react-renderer';

// Gruvbox dark (hard contrast) Prism theme — mirrors the design system's
// syntax tokens. prism-react-renderer applies inline styles, so the syntax
// palette lives here rather than in custom.css.
const gruvboxDark: PrismTheme = {
  plain: {color: '#ebdbb2', backgroundColor: '#282828'},
  styles: [
    {types: ['comment', 'prolog', 'cdata'], style: {color: '#928374', fontStyle: 'italic'}},
    {types: ['punctuation'], style: {color: '#bdae93'}},
    {types: ['keyword', 'tag', 'selector', 'important', 'atrule'], style: {color: '#fb4934'}},
    {types: ['string', 'char', 'attr-value', 'regex'], style: {color: '#b8bb26'}},
    {types: ['function', 'function-variable', 'method'], style: {color: '#b8bb26'}},
    {types: ['number', 'boolean', 'constant', 'symbol'], style: {color: '#d3869b'}},
    {types: ['operator', 'entity', 'url'], style: {color: '#fe8019'}},
    {types: ['class-name', 'maybe-class-name'], style: {color: '#fabd2f'}},
    {types: ['builtin', 'namespace'], style: {color: '#8ec07c'}},
    {types: ['variable', 'attr-name', 'property'], style: {color: '#83a598'}},
    {types: ['deleted'], style: {color: '#fb4934'}},
    {types: ['inserted'], style: {color: '#b8bb26'}},
    {types: ['changed'], style: {color: '#fabd2f'}},
  ],
};

const config: Config = {
  title: 'Prisma AIRS SDK',
  tagline: 'TypeScript SDK for Palo Alto Networks Prisma AIRS',
  favicon: 'img/logo.svg',

  future: {
    v4: true,
  },

  url: 'https://cdot65.github.io',
  baseUrl: '/prisma-airs-sdk/',

  organizationName: 'cdot65',
  projectName: 'prisma-airs-sdk',

  onBrokenLinks: 'throw',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    // .md → CommonMark (safe for code-heavy guides + TypeDoc output), .mdx → MDX
    format: 'detect',
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  themes: ['@docusaurus/theme-mermaid'],

  // The API reference under docs/reference/api is generated by TypeDoc
  // (`npm run docs:api` from the repo root) before the Docusaurus build.

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
          editUrl: 'https://github.com/cdot65/prisma-airs-sdk/tree/main/docs-site/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: 'img/social-card.png',
    // The Gruvbox design system is dark, hard-contrast only.
    colorMode: {
      defaultMode: 'dark',
      disableSwitch: true,
      respectPrefersColorScheme: false,
    },
    navbar: {
      title: 'Prisma AIRS SDK',
      logo: {
        alt: 'Prisma AIRS SDK',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docs',
          position: 'left',
          label: 'Docs',
        },
        {
          to: '/reference/api/',
          label: 'API Reference',
          position: 'left',
        },
        {
          href: 'https://www.npmjs.com/package/@cdot65/prisma-airs-sdk',
          label: 'npm',
          position: 'right',
        },
        {
          href: 'https://github.com/cdot65/prisma-airs-sdk',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {label: 'Getting Started', to: '/getting-started/installation'},
            {label: 'Guides', to: '/guides/scan-api'},
            {label: 'API Reference', to: '/reference/api/'},
          ],
        },
        {
          title: 'More',
          items: [
            {label: 'npm', href: 'https://www.npmjs.com/package/@cdot65/prisma-airs-sdk'},
            {label: 'GitHub', href: 'https://github.com/cdot65/prisma-airs-sdk'},
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} cdot65. Built with Docusaurus.`,
    },
    prism: {
      theme: gruvboxDark,
      darkTheme: gruvboxDark,
      additionalLanguages: ['bash', 'json', 'diff'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
