import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import airsTheme from './src/css/prism-airs';

const config: Config = {
  title: 'Prisma AIRS SDK',
  tagline: 'TypeScript SDK for Palo Alto Networks Prisma AIRS',
  favicon: 'img/brand-logo.png',

  future: {
    v4: true,
  },

  url: 'https://cdot65.github.io',
  baseUrl: '/prisma-airs-sdk/',

  organizationName: 'cdot65',
  projectName: 'prisma-airs-sdk',

  onBrokenLinks: 'throw',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    // .md → CommonMark (safe for code-heavy guides + TypeDoc output), .mdx → MDX
    format: 'detect',
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  themes: ['@docusaurus/theme-mermaid'],

  // The API reference under docs/reference/api is generated by TypeDoc
  // (`npm run docs:api` from the repo root) before the Docusaurus build.

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
          editUrl: 'https://git.cdot.io/cdot/prisma-airs-sdk/_edit/main/docs-site/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    mermaid: {theme: {light: 'dark', dark: 'dark'}, options: {themeVariables: {
      background: '#030609', primaryColor: '#061b29', primaryTextColor: '#f5f8fa',
      primaryBorderColor: '#00ddf2', lineColor: '#8999a6', secondaryColor: '#0b293b', tertiaryColor: '#061b29',
    }}},
    image: 'img/brand-logo.png',
    // Prisma AIRS brand palette uses a dark canvas.
    colorMode: {
      defaultMode: 'dark',
      disableSwitch: true,
      respectPrefersColorScheme: false,
    },
    navbar: {
      title: 'Prisma AIRS SDK',
      logo: {
        alt: 'Prisma AIRS SDK',
        src: 'img/brand-logo.png',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docs',
          position: 'left',
          label: 'Docs',
        },
        {
          to: '/reference/api/',
          label: 'API Reference',
          position: 'left',
        },
        {
          href: 'https://www.npmjs.com/package/@cdot65/prisma-airs-sdk',
          label: 'npm',
          position: 'right',
        },
        {
          href: 'https://git.cdot.io/cdot/prisma-airs-sdk',
          label: 'Forgejo',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {label: 'Getting Started', to: '/getting-started/installation'},
            {label: 'Guides', to: '/guides/scan-api'},
            {label: 'API Reference', to: '/reference/api/'},
          ],
        },
        {
          title: 'More',
          items: [
            {label: 'npm', href: 'https://www.npmjs.com/package/@cdot65/prisma-airs-sdk'},
            {label: 'Forgejo', href: 'https://git.cdot.io/cdot/prisma-airs-sdk'},
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} cdot65. Built with Docusaurus.`,
    },
    prism: {
      theme: airsTheme,
      darkTheme: airsTheme,
      additionalLanguages: ['bash', 'json', 'diff'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
