import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: 'Prisma AIRS SDK',
  tagline: 'TypeScript SDK for Palo Alto Networks Prisma AIRS',
  favicon: 'img/logo.svg',

  future: {
    v4: true,
  },

  url: 'https://cdot65.github.io',
  baseUrl: '/prisma-airs-sdk/',

  organizationName: 'cdot65',
  projectName: 'prisma-airs-sdk',

  onBrokenLinks: 'throw',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    // .md → CommonMark (safe for code-heavy guides + TypeDoc output), .mdx → MDX
    format: 'detect',
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  themes: ['@docusaurus/theme-mermaid'],

  // The API reference under docs/reference/api is generated by TypeDoc
  // (`npm run docs:api` from the repo root) before the Docusaurus build.

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
          editUrl: 'https://github.com/cdot65/prisma-airs-sdk/tree/main/docs-site/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'Prisma AIRS SDK',
      logo: {
        alt: 'Prisma AIRS SDK',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docs',
          position: 'left',
          label: 'Docs',
        },
        {
          to: '/reference/api/',
          label: 'API Reference',
          position: 'left',
        },
        {
          href: 'https://www.npmjs.com/package/@cdot65/prisma-airs-sdk',
          label: 'npm',
          position: 'right',
        },
        {
          href: 'https://github.com/cdot65/prisma-airs-sdk',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {label: 'Getting Started', to: '/getting-started/installation'},
            {label: 'Guides', to: '/guides/scan-api'},
            {label: 'API Reference', to: '/reference/api/'},
          ],
        },
        {
          title: 'More',
          items: [
            {label: 'npm', href: 'https://www.npmjs.com/package/@cdot65/prisma-airs-sdk'},
            {label: 'GitHub', href: 'https://github.com/cdot65/prisma-airs-sdk'},
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} cdot65. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['bash', 'json'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
