import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/configuration',
        'getting-started/environment-variables',
        'getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/scan-api',
        'guides/management-api',
        'guides/oauth-lifecycle',
        'guides/model-security-api',
        'guides/red-team-api',
        {
          type: 'category',
          label: 'DLP',
          items: [
            'guides/dlp/data-filtering-profiles',
            'guides/dlp/data-patterns',
            'guides/dlp/data-profiles',
            'guides/dlp/dictionaries',
          ],
        },
        {
          type: 'category',
          label: 'Cookbook',
          items: ['guides/cookbook/api-key-rotation'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer',
      items: [
        'developer/architecture',
        'developer/development',
        'developer/api-design-versioning',
        'developer/error-handling',
      ],
    },
    {
      type: 'category',
      label: 'About',
      items: ['about/release-notes', 'about/license'],
    },
  ],

  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'reference/api/index'},
      items: [{type: 'autogenerated', dirName: 'reference/api'}],
    },
  ],
};

export default sidebars;
